my_project:
    settings:
        - __init__.py
        - dev.py
        - prod.py
    mainapp:
        - templates:
            mainapp:
                - base.html
                - index.html
        - __init__.py
        - models.py
        - views.py
    authapp:
        - __init__.py
        - models.py
        - views.py
        - templates:
            authapp:
                - base.html
                - index.html
